# Generated by Django 4.2.30 on 2026-07-28 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="客户名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="客户编码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="产品名称")),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="产品编码"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "db_table": "product",
                "ordering": ["-priority", "code"],
            },
        ),
        migrations.CreateModel(
            name="ActualProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("production_date", models.DateField(verbose_name="生产日期")),
                ("quantity", models.IntegerField(verbose_name="实际产量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "实际产量",
                "verbose_name_plural": "实际产量",
                "db_table": "actual_production",
                "ordering": ["-production_date", "product"],
            },
        ),
        migrations.CreateModel(
            name="WarningRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warning_date", models.DateField(verbose_name="预警日期")),
                ("planned_quantity", models.IntegerField(verbose_name="计划产量")),
                ("actual_quantity", models.IntegerField(verbose_name="实际产量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认"),
                            ("shipped", "已出货"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "handler",
                    models.CharField(blank=True, max_length=100, verbose_name="处理人"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警记录",
                "verbose_name_plural": "预警记录",
                "db_table": "warning_record",
                "ordering": ["-warning_date", "product"],
                "unique_together": {("product", "warning_date")},
            },
        ),
        migrations.CreateModel(
            name="ProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                ("month", models.IntegerField(verbose_name="月份")),
                ("planned_quantity", models.IntegerField(verbose_name="计划产量")),
                (
                    "import_batch",
                    models.CharField(max_length=100, verbose_name="导入批次"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产量计划",
                "verbose_name_plural": "产量计划",
                "db_table": "production_plan",
                "ordering": ["-year", "-month", "product"],
                "unique_together": {("product", "year", "month")},
            },
        ),
    ]
