# Generated by Django 4.2.30 on 2026-07-30 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='月份')),
                ('fab', models.CharField(max_length=50, verbose_name='Fab')),
                ('bu', models.CharField(max_length=50, verbose_name='BU')),
                ('customer', models.CharField(max_length=100, verbose_name='客户')),
                ('material_code_52', models.CharField(max_length=100, verbose_name='52阶料号')),
                ('mode', models.CharField(max_length=50, verbose_name='Mode')),
                ('finished_product_code', models.CharField(max_length=100, verbose_name='成品料号')),
                ('next_month_mps', models.IntegerField(default=0, verbose_name='下个月MPS数量')),
                ('next_next_month_mps', models.IntegerField(default=0, verbose_name='下下个月MPS数量')),
                ('box_quantity', models.IntegerField(default=0, verbose_name='每箱数量')),
                ('sample_request_qty', models.IntegerField(default=0, verbose_name='需求送片量')),
                ('qe_decision', models.CharField(blank=True, choices=[('是', '是'), ('否', '否'), ('待定', '待定'), ('', '未填写')], default='', max_length=20, verbose_name='QE决议是否送样')),
                ('gpc_decision', models.CharField(blank=True, choices=[('是', '是'), ('否', '否'), ('待定', '待定'), ('', '未填写')], default='', max_length=20, verbose_name='GPC决议是否送样')),
                ('final_decision', models.CharField(blank=True, choices=[('是', '是'), ('否', '否'), ('待定', '待定'), ('', '未填写')], default='', max_length=20, verbose_name='最终决议是否送样')),
                ('sample_remark', models.TextField(blank=True, default='', verbose_name='需求数量备注')),
                ('q_order', models.CharField(blank=True, default='', max_length=100, verbose_name='Q工单')),
                ('box_number', models.CharField(blank=True, default='', max_length=50, verbose_name='箱号')),
                ('sample_date', models.DateField(blank=True, null=True, verbose_name='送样日期')),
                ('exception_note', models.TextField(blank=True, default='', verbose_name='异常确认说明')),
                ('import_batch', models.CharField(blank=True, default='', max_length=100, verbose_name='导入批次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '送样管理计划',
                'verbose_name_plural': '送样管理计划',
                'db_table': 'sample_plan',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarningRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('condition_type', models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值')], max_length=20, verbose_name='条件类型')),
                ('operator', models.CharField(choices=[('>=', '大于等于'), ('>', '大于'), ('<=', '小于等于'), ('<', '小于'), ('==', '等于')], max_length=2, verbose_name='运算符')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
                'db_table': 'warning_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['code'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterModelOptions(
            name='productionplan',
            options={'ordering': ['-year', '-month'], 'verbose_name': '生产计划', 'verbose_name_plural': '生产计划'},
        ),
        migrations.AlterModelOptions(
            name='warningrecord',
            options={'ordering': ['-warning_date'], 'verbose_name': '预警记录', 'verbose_name_plural': '预警记录'},
        ),
        migrations.AlterUniqueTogether(
            name='warningrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='productionplan',
            name='import_batch',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pcs', max_length=20, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实际产量'),
        ),
        migrations.AddField(
            model_name='productionplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='warningrecord',
            name='achievement_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='达成率(%)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='客户代码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='产品代码'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='productionplan',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='计划产量'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实际产量'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='handler',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='计划产量'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='remark',
            field=models.TextField(blank=True, default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('producing', '生产中'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='ActualProduction',
        ),
        migrations.AddField(
            model_name='warningrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='留空表示应用于所有产品', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='产品'),
        ),
    ]
