# Generated by Django 4.2.30 on 2026-07-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sampleplan_warningrule_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bu',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='BU'),
        ),
        migrations.AddField(
            model_name='product',
            name='fab',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Fab'),
        ),
        migrations.AddField(
            model_name='product',
            name='finished_product_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='成品料号'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_code_52',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='52阶料号'),
        ),
        migrations.AddField(
            model_name='product',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='bu',
            field=models.CharField(blank=True, default='', help_text='匹配 BU 字段，留空不限制', max_length=50, verbose_name='BU'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='指定客户（可选）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='fab',
            field=models.CharField(blank=True, default='', help_text='匹配 Fab 字段，留空不限制', max_length=50, verbose_name='Fab'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='finished_product_code',
            field=models.CharField(blank=True, default='', help_text='匹配 成品料号，留空不限制', max_length=100, verbose_name='成品料号'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='material_code_52',
            field=models.CharField(blank=True, default='', help_text='匹配 52阶料号，留空不限制', max_length=100, verbose_name='52阶料号'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='mode',
            field=models.CharField(blank=True, default='', help_text='匹配 Mode 字段，留空不限制', max_length=50, verbose_name='Mode'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值')], default='cumulative_vs_plan', max_length=20, verbose_name='条件类型'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='operator',
            field=models.CharField(choices=[('>=', '大于等于'), ('>', '大于'), ('<=', '小于等于'), ('<', '小于'), ('==', '等于')], default='>=', max_length=2, verbose_name='运算符'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='product',
            field=models.ForeignKey(blank=True, help_text='指定特定产品（可选）', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='具体产品'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='阈值'),
        ),
    ]
