# Generated by Django 4.2.30 on 2026-07-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_bu_product_fab_product_finished_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='serial_number',
            field=models.IntegerField(default=0, verbose_name='序号'),
        ),
    ]
