# Generated by Django 4.2.30 on 2026-07-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sampleplan_source_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleplan',
            options={'ordering': ['-plan_year', '-plan_month', 'serial_number', 'id'], 'verbose_name': '送样管理计划', 'verbose_name_plural': '送样管理计划'},
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_month',
            field=models.IntegerField(default=1, verbose_name='计划月份'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_year',
            field=models.IntegerField(default=2026, verbose_name='计划年份'),
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('day', models.IntegerField(default=1, verbose_name='日')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('daily_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='当日产量')),
                ('cumulative_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计产量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '按日产量',
                'verbose_name_plural': '按日产量',
                'db_table': 'daily_production',
                'ordering': ['-production_date', 'product'],
                'unique_together': {('product', 'production_date')},
            },
        ),
    ]
