# Generated by Trae AI on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sampleplan_options_sampleplan_plan_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='source_side',
            field=models.CharField(
                blank=True,
                choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B'), ('', '未指定')],
                default='',
                help_text='双 Excel 合并时此行来自哪个文件：A(仅A) / B(仅B) / A+B(两边都有)',
                max_length=10,
                verbose_name='来源',
            ),
        ),
    ]
