# Generated by Django 4.2.30 on 2026-08-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sampleplan_source_side'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sampleplan',
            options={'ordering': ['-plan_year', '-plan_month', 'serial_number', 'id'], 'verbose_name': '每月计划', 'verbose_name_plural': '每月计划'},
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='检测时间'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='is_unplanned',
            field=models.BooleanField(default=False, help_text='由预警系统自动加入：原本不在计划中但已实际生产的产品。', verbose_name='计划外产品'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='unplanned_reason',
            field=models.CharField(blank=True, default='', help_text='自动加入时的原因描述，例如"实际产量 > 0 但未匹配到任何月度计划"', max_length=200, verbose_name='计划外原因'),
        ),
        migrations.AlterField(
            model_name='sampleplan',
            name='mode',
            field=models.CharField(max_length=50, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='warningrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('producing', '生产中'), ('closed', '已处理')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='mode',
            field=models.CharField(blank=True, default='', help_text='匹配 Model 字段，留空不限制', max_length=50, verbose_name='Model'),
        ),
    ]
