# Generated by Django 4.2.30 on 2026-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sampleplan_options_sampleplan_detected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningrule',
            name='applies_to',
            field=models.CharField(default='warning,plan_import', help_text='逗号分隔。例：warning（预警） / plan_import（导入筛选） / warning,plan_import（两者）', max_length=60, verbose_name='应用场景'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值'), ('request_qty', '需求送片量 vs 阈值'), ('next_month_mps', '下个月MPS vs 阈值'), ('next_next_month_mps', '下下个月MPS vs 阈值'), ('box_quantity', '每箱数量 vs 阈值')], default='cumulative_vs_plan', max_length=20, verbose_name='条件类型'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='operator',
            field=models.CharField(choices=[('>=', '大于等于'), ('>', '大于'), ('<=', '小于等于'), ('<', '小于'), ('==', '等于'), ('<>', '不等于')], default='>=', max_length=2, verbose_name='运算符'),
        ),
    ]
