# Generated by Django 4.2.30 on 2026-08-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_warningrule_applies_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warningrule',
            name='applies_to',
        ),
        migrations.AddField(
            model_name='warningrule',
            name='rule_type',
            field=models.CharField(choices=[('warning', '预警监控'), ('plan_import', '初步筛选')], db_index=True, default='warning', help_text='warning=预警规则（预警监控用）；plan_import=筛选规则（Excel导入用）', max_length=20, verbose_name='规则类型'),
        ),
    ]
