# Generated by Django 4.2.30 on 2026-08-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_warningrule_applies_to_warningrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值'), ('request_qty', '需求送片量 vs 阈值'), ('next_month_mps', '下个月MPS vs 阈值'), ('next_next_month_mps', '下下个月MPS vs 阈值'), ('box_quantity', '每箱数量 vs 阈值'), ('plan_a_8_31_qty', '8/31 月底数量 vs 阈值'), ('plan_a_9_30_qty', '9/30 月底数量 vs 阈值'), ('plan_a_10_31_qty', '10/31 月底数量 vs 阈值')], default='cumulative_vs_plan', max_length=20, verbose_name='条件类型'),
        ),
    ]
