# Generated by Django 4.2.30 on 2026-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_warningrule_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_10_31_qty',
            field=models.IntegerField(default=0, help_text='计划A表10/31列的值', verbose_name='10/31月底数量'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_8_31_qty',
            field=models.IntegerField(default=0, help_text='计划A表8/31列的值', verbose_name='8/31月底数量'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_9_30_qty',
            field=models.IntegerField(default=0, help_text='计划A表9/30列的值', verbose_name='9/30月底数量'),
        ),
    ]
