# Generated by Django 4.2.30 on 2026-08-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sampleplan_plan_a_10_31_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_other_monthly_qty',
            field=models.TextField(blank=True, default='{}', help_text='除8/9/10月外的其他月份最后一天数量，JSON 字符串 {"4/30": 100, "11/30": 200}', verbose_name='其他月份月底数量'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='target_month_day',
            field=models.CharField(blank=True, default='', help_text='当条件类型=其他月份月底数量 时必填，如 4/30、11/30；其他场景留空', max_length=10, verbose_name='目标月日'),
        ),
        migrations.AlterField(
            model_name='sampleplan',
            name='plan_a_10_31_qty',
            field=models.IntegerField(default=0, help_text='计划A表10月最后一天列的值', verbose_name='10/31月底数量'),
        ),
        migrations.AlterField(
            model_name='sampleplan',
            name='plan_a_8_31_qty',
            field=models.IntegerField(default=0, help_text='计划A表8月最后一天列的值', verbose_name='8/31月底数量'),
        ),
        migrations.AlterField(
            model_name='sampleplan',
            name='plan_a_9_30_qty',
            field=models.IntegerField(default=0, help_text='计划A表9月最后一天列的值', verbose_name='9/30月底数量'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值'), ('request_qty', '需求送片量 vs 阈值'), ('next_month_mps', '下个月MPS vs 阈值'), ('next_next_month_mps', '下下个月MPS vs 阈值'), ('box_quantity', '每箱数量 vs 阈值'), ('plan_a_8_31_qty', '8/31 月底数量 vs 阈值'), ('plan_a_9_30_qty', '9/30 月底数量 vs 阈值'), ('plan_a_10_31_qty', '10/31 月底数量 vs 阈值'), ('plan_a_other_qty', '其他月份月底数量 vs 阈值（搭配 target_month_day）')], default='cumulative_vs_plan', max_length=20, verbose_name='条件类型'),
        ),
    ]
