# Generated by Django 4.2.30 on 2026-08-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sampleplan_plan_a_other_monthly_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_middle_month_day',
            field=models.CharField(blank=True, default='', help_text='中间那一列的月日，如 5/31、9/30；空表示导入时未识别到月底列', max_length=10, verbose_name='中间月月日'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_middle_qty',
            field=models.IntegerField(default=0, help_text='导入计划A时自动取三个日期列里中间那个的底下的数字（如 4/30/5/31/6/30 → 取 5/31）', verbose_name='中间月月底数量'),
        ),
        migrations.AddField(
            model_name='warningrule',
            name='effective_month',
            field=models.IntegerField(blank=True, help_text='当条件类型=计划A中间月月底数量 时必填，1-12；表示对哪个月份生效（通常填中间月的下一个月）', null=True, verbose_name='生效月份'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值'), ('request_qty', '需求送片量 vs 阈值'), ('next_month_mps', '下个月MPS vs 阈值'), ('next_next_month_mps', '下下个月MPS vs 阈值'), ('box_quantity', '每箱数量 vs 阈值'), ('plan_a_8_31_qty', '8/31 月底数量 vs 阈值'), ('plan_a_9_30_qty', '9/30 月底数量 vs 阈值'), ('plan_a_10_31_qty', '10/31 月底数量 vs 阈值'), ('plan_a_other_qty', '其他月份月底数量 vs 阈值（搭配 target_month_day）'), ('plan_a_middle_qty', '计划A中间月月底数量 vs 阈值（对下个月生效，搭配 effective_month）')], default='cumulative_vs_plan', max_length=20, verbose_name='条件类型'),
        ),
    ]
