# Generated by Django 4.2.30 on 2026-08-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sampleplan_plan_a_middle_month_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_second_last_month_day',
            field=models.CharField(blank=True, default='', help_text='倒数第二个月底列的月日，如 9/30、7/31；空表示导入时未识别到月底列', max_length=10, verbose_name='倒数第二个月底月日'),
        ),
        migrations.AddField(
            model_name='sampleplan',
            name='plan_a_second_last_qty',
            field=models.IntegerField(default=0, help_text='导入计划A时自动取某月最后一天列的倒数第二列（如 8/31、9/30、10/31 → 取 9/30）的数字', verbose_name='倒数第二个月底数量'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='condition_type',
            field=models.CharField(choices=[('cumulative_vs_plan', '实际产量累计值 vs 计划值'), ('request_qty', '需求送片量 vs 阈值'), ('next_month_mps', '下个月MPS vs 阈值'), ('next_next_month_mps', '下下个月MPS vs 阈值'), ('box_quantity', '每箱数量 vs 阈值'), ('plan_a_8_31_qty', '8/31 月底数量 vs 阈值'), ('plan_a_9_30_qty', '9/30 月底数量 vs 阈值'), ('plan_a_10_31_qty', '10/31 月底数量 vs 阈值'), ('plan_a_other_qty', '其他月份月底数量 vs 阈值（搭配 target_month_day）'), ('plan_a_middle_qty', '计划A中间月月底数量 vs 阈值（对下个月生效，搭配 effective_month）'), ('plan_a_second_last_qty', '计划A倒数第二个月底数量 vs 阈值（对下个月生效，搭配 effective_month）')], default='cumulative_vs_plan', max_length=32, verbose_name='条件类型'),
        ),
        migrations.AlterField(
            model_name='warningrule',
            name='effective_month',
            field=models.IntegerField(blank=True, help_text='当条件类型=计划A中间月/倒数第二个月底数量 时必填，1-12；表示对哪个月份生效', null=True, verbose_name='生效月份'),
        ),
    ]
