# Generated by Django 4.2.30 on 2026-08-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_sampleplan_plan_a_second_last_month_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='Model')),
                ('material_code_52', models.CharField(blank=True, default='', max_length=100, verbose_name='52阶料号')),
                ('box_quantity', models.IntegerField(default=0, verbose_name='满箱量')),
                ('customer', models.CharField(blank=True, default='', max_length=100, verbose_name='客户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '录入表1',
                'verbose_name_plural': '录入表1',
                'db_table': 'entry_table',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='OrtRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='如 PD/TV/DT/MIB/SET；S13 专用可填 S13', max_length=20, verbose_name='Type')),
                ('source', models.CharField(choices=[('ALL', '全部'), ('S13', 'S13_DPS'), ('MONTHLY', 'Monthly input target')], default='ALL', max_length=10, verbose_name='来源')),
                ('operator', models.CharField(choices=[('>=', '大于等于'), ('>', '大于'), ('<=', '小于等于'), ('<', '小于'), ('==', '等于'), ('<>', '不等于')], default='>=', max_length=2, verbose_name='运算符')),
                ('threshold', models.IntegerField(default=0, verbose_name='最低需求数量阈值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'ORT规则',
                'verbose_name_plural': 'ORT规则',
                'db_table': 'ort_rule',
                'ordering': ['source', 'type_name'],
            },
        ),
        migrations.CreateModel(
            name='PreplanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=64, verbose_name='导入批次')),
                ('plan_year', models.IntegerField(db_index=True, default=2026, verbose_name='计划年份')),
                ('serial_number', models.IntegerField(default=0, verbose_name='序号')),
                ('status', models.CharField(choices=[('kept', '通过筛选'), ('filtered', '被过滤')], db_index=True, default='kept', max_length=10, verbose_name='状态')),
                ('source', models.CharField(choices=[('S13_DPS', 'S13_DPS'), ('Monthly_Input', 'Monthly_Input')], default='S13_DPS', max_length=20, verbose_name='来源文件')),
                ('plan_month_label', models.CharField(blank=True, default='', max_length=20, verbose_name='预排月份')),
                ('table_date', models.CharField(blank=True, default='', max_length=20, verbose_name='制表日期')),
                ('type', models.CharField(blank=True, default='', max_length=20, verbose_name='Type')),
                ('fab', models.CharField(blank=True, default='', max_length=50, verbose_name='FAB')),
                ('material_code_52', models.CharField(blank=True, default='', max_length=100, verbose_name='52阶料号')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='Model')),
                ('pn', models.CharField(blank=True, default='', max_length=100, verbose_name='P/N')),
                ('customer', models.CharField(blank=True, default='', max_length=100, verbose_name='客户')),
                ('n1_dps', models.IntegerField(default=0, verbose_name='N+1 DPS')),
                ('n2_dps', models.IntegerField(default=0, verbose_name='N+2 DPS')),
                ('box_quantity', models.IntegerField(default=0, verbose_name='满箱量')),
                ('request_qty', models.IntegerField(default=0, verbose_name='需求数量(PCS)')),
                ('issue_qty_box', models.IntegerField(default=0, verbose_name='领用数量-箱')),
                ('issue_qty_pcs', models.IntegerField(default=0, verbose_name='领用数量-零数片')),
                ('ort_ok', models.CharField(blank=True, default='', max_length=4, verbose_name='是否满足ORT量')),
                ('qe_requirement', models.CharField(blank=True, default='', max_length=100, verbose_name='QE需求')),
                ('qe_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='QERemark')),
                ('ra_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='RA REMARK')),
                ('gpc_reply', models.CharField(blank=True, default='', max_length=20, verbose_name='GPC回复')),
                ('q_order', models.CharField(blank=True, default='', max_length=100, verbose_name='Q工单')),
                ('box_number', models.CharField(blank=True, default='', max_length=50, verbose_name='箱号')),
                ('sample_date', models.DateField(blank=True, null=True, verbose_name='送样日期')),
                ('mtd_output', models.CharField(blank=True, default='', max_length=50, verbose_name='MTD OUTPUT监控')),
                ('judge', models.CharField(blank=True, default='', max_length=50, verbose_name='Judge')),
                ('filter_reason', models.TextField(blank=True, default='', verbose_name='过滤原因')),
                ('missing_fields', models.TextField(blank=True, default='', verbose_name='缺失字段')),
                ('source_file_name', models.CharField(blank=True, default='', max_length=300, verbose_name='源文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '预排筛选结果',
                'verbose_name_plural': '预排筛选结果',
                'db_table': 'preplan_row',
                'ordering': ['-plan_year', 'serial_number', 'id'],
            },
        ),
    ]
