# Generated by Django 6.1 on 2026-08-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_entrytable_ortrule_preplanrow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ortrule",
            name="type_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="如 PD/TV/DT/MIB/SET；S13 专用可填 S13；留空表示对所有 Type 生效",
                max_length=20,
                verbose_name="Type",
            ),
        ),
    ]
