# Generated by Django 6.1 on 2026-08-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_ortrule_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrytable",
            options={
                "ordering": ["model"],
                "verbose_name": "基础资料表",
                "verbose_name_plural": "基础资料表",
            },
        ),
        migrations.AddField(
            model_name="preplanrow",
            name="exported",
            field=models.BooleanField(default=False, verbose_name="是否导出到审核决议"),
        ),
    ]
