# Generated by Django 6.1 on 2026-08-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_preplanrow_exported"),
    ]

    operations = [
        migrations.AddField(
            model_name="preplanrow",
            name="is_plan_external",
            field=models.BooleanField(
                default=False,
                help_text="MTD SQL 查到但预排计划中不存在的料号，标记为计划外",
                verbose_name="计划外",
            ),
        ),
    ]
