# Generated by Django 6.1 on 2026-08-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_preplanrow_plan_external"),
    ]

    operations = [
        migrations.AddField(
            model_name="preplanrow",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="决议中心保存到存档中心后置 True，表示数据已最终定版",
                verbose_name="已存档定版",
            ),
        ),
        migrations.AlterField(
            model_name="sampleplan",
            name="plan_a_other_monthly_qty",
            field=models.TextField(
                blank=True,
                default="{}",
                help_text='所有月份的月底数量（含8/9/10月），JSON 字符串 {"4/30": 100, "8/31": 200, "11/30": 300}',
                verbose_name="其他月份月底数量",
            ),
        ),
    ]
