# -*- coding: utf-8 -*-
# Generated by Django 4.2 手动创建：PreplanRow 新增 OQC Hold 列
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_preplan_inserted_and_bim_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='preplanrow',
            name='oqc_hold',
            field=models.CharField(blank=True, default='', help_text='OQC Hold 标记，仅允许 Y / N / 空', max_length=4, verbose_name='OQC Hold'),
        ),
    ]
