# Generated by Django 6.1.1 on 2026-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_botdatacache_alter_preplanrow_inserted_to_preplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QcAgentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_id', models.CharField(help_text='沿用原版 id 生成规则，便于汇入旧备份', max_length=32, unique=True, verbose_name='原前端ID')),
                ('group', models.CharField(max_length=32, verbose_name='功能群组')),
                ('subtype', models.CharField(max_length=32, verbose_name='子类型(Function)')),
                ('work', models.CharField(max_length=30, verbose_name='工作(英文)')),
                ('seq', models.CharField(max_length=3, verbose_name='流水码')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Agent 名称')),
                ('arch', models.CharField(max_length=32, verbose_name='技术架构')),
                ('status', models.CharField(default='开发中', help_text='开发中 / 使用中 / 废除', max_length=8, verbose_name='状态')),
                ('dev', models.CharField(blank=True, default='', max_length=32, verbose_name='开发者')),
                ('desc', models.CharField(blank=True, default='', max_length=255, verbose_name='专案说明')),
                ('success', models.CharField(blank=True, default='', max_length=16, verbose_name='成功率(%)')),
                ('accuracy', models.CharField(blank=True, default='', max_length=16, verbose_name='准确率(%)')),
                ('token', models.CharField(blank=True, default='', max_length=16, verbose_name='Token消耗')),
                ('time', models.CharField(blank=True, default='', max_length=16, verbose_name='单次耗时(s)')),
                ('btype', models.CharField(blank=True, default='', help_text='耗时 / 人力 / 空', max_length=8, verbose_name='效益类型')),
                ('bval', models.CharField(blank=True, default='', max_length=16, verbose_name='效益数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'QC_AI_TEAM Agent 专案',
                'verbose_name_plural': 'QC_AI_TEAM Agent 专案',
                'db_table': 'qc_agent_project',
                'ordering': ['group', 'subtype', 'work', 'seq', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QcAgentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('group', '功能群组'), ('subtype', '子类型(Function)'), ('arch', '技术架构'), ('dev', '开发者')], max_length=16, verbose_name='分类类型')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('is_builtin', models.BooleanField(default=False, help_text='内建项不可删除（与原版一致）', verbose_name='内建')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QC_AI_TEAM 分类项',
                'verbose_name_plural': 'QC_AI_TEAM 分类项',
                'db_table': 'qc_agent_category',
                'ordering': ['kind', 'sort', 'id'],
                'unique_together': {('kind', 'name')},
            },
        ),
    ]
