# Generated by Django 6.1.1 on 2026-09-20 02:47
# ★ 2026-09-20 手工追加：旧数据把 plan_ym 从 plan_month_label 反解回填。

import re

from django.db import migrations, models


_YM_PAT = re.compile(r'(?:(\d{4})\s*年)?\s*(\d{1,2})\s*月')


def _ym_from_label(label, fallback_year):
    """'9月' → 由 fallback_year 补年；'2027年2月' → 直接用标签里的年份。解析不出返回 0（未归类）。"""
    m = _YM_PAT.search(str(label or ''))
    if not m:
        return 0
    try:
        year = int(m.group(1)) if m.group(1) else int(fallback_year or 0)
        month = int(m.group(2))
    except (TypeError, ValueError):
        return 0
    if not (1 <= month <= 12) or not (2000 <= year <= 2100):
        return 0
    return year * 100 + month


def forwards(apps, schema_editor):
    """按 plan_month_label 回填 plan_ym。

    为什么需要：加字段前所有历史行 plan_ym 都是默认 0，若直接上线会导致
    预排/决议/预警/存档页按月份筛选时全部落进「未归类」，看不到任何数据。
    年份优先取标签里显式的 4 位年份（S13/S11 跨年时标签会写成「2027年2月」），
    没有显式年份时用该行的 plan_year（文件年份）。
    """
    PreplanRow = apps.get_model('core', 'PreplanRow')
    batch = []
    for row in PreplanRow.objects.all().iterator(chunk_size=500):
        ym = _ym_from_label(row.plan_month_label, row.plan_year)
        if ym:
            row.plan_ym = ym
            batch.append(row)
        if len(batch) >= 500:
            PreplanRow.objects.bulk_update(batch, ['plan_ym'])
            batch = []
    if batch:
        PreplanRow.objects.bulk_update(batch, ['plan_ym'])


def backwards(apps, schema_editor):
    PreplanRow = apps.get_model('core', 'PreplanRow')
    PreplanRow.objects.update(plan_ym=0)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_qcagentproject_qcagentcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="preplanrow",
            name="plan_ym",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="预排年月(YYYYMM)"
            ),
        ),
        migrations.AlterField(
            model_name="preplanrow",
            name="inserted_to_preplan",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="计划外实时监控项是否插入预排筛选（默认不插入；预警界面可切换）",
                verbose_name="插入预排筛选",
            ),
        ),
        migrations.AlterField(
            model_name="preplanrow",
            name="source",
            field=models.CharField(
                choices=[
                    ("S13_DPS", "S13_DPS"),
                    ("Monthly_Input", "Monthly_Input"),
                    ("MTD_EXTERNAL", "计划外"),
                ],
                default="S13_DPS",
                max_length=20,
                verbose_name="来源文件",
            ),
        ),
        # ★ 旧数据回填：必须放在 AddField 之后
        migrations.RunPython(forwards, backwards),
    ]
